telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"

notion:
  api_token: "YOUR_NOTION_API_TOKEN"
  database_id: "YOUR_NOTION_DATABASE_ID"

data:
  max_watch_days: 5

api:
  provider: "yfinance"
  token: ""
